version: '3.8'
services:
  # Your existing database (e.g., Postgres or MySQL)
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Adding Redis for Sessions
  redis:
    image: redis:alpine
    container_name: session_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:


# version: '3.8'
# services:
#   db:
#     image: postgres:15
#     container_name: nest_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: user123
#       POSTGRES_PASSWORD: password123
#       POSTGRES_DB: my_database
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: